# -*- coding: utf-8 -*-
"""movies.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J_z4h3R6ENieJtzKkWSwrplDVJhknJo5
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('movies_metadata.csv')

df.head()

df.columns

df.describe()

df.columns

df.info()

df.shape

df.isnull().sum()

df.duplicated().sum()

df = df.drop_duplicates().reset_index(drop=True)
df.duplicated().sum()

dfn = df[['title','overview','genres','tagline','vote_average','popularity']]
dfn

dfn = dfn.dropna(subset = ['title'])
dfn.shape

dfn.isnull().sum()

dfn['overview'] = dfn['overview'].fillna('')
dfn['tagline'] = dfn['tagline'].fillna('')
dfn.isnull().sum()

dfn.iloc[0]['genres']

import ast
dfn['genres'] = dfn['genres'].apply(lambda x :" ".join([i['name'] for i in ast.literal_eval(x)]))

dfn.head()

dfn['tagline'] = dfn['tagline'].fillna('')
dfn.isnull().sum()

dfn['tags'] = dfn['overview'] + '' + dfn['genres'] + '' + dfn['tagline']
dfn.head()

dfn['tags'][1]

import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

nltk.download('stopwords')
nltk.download('wordnet')

stop_words = set(stopwords.words('english'))
lammatizer = WordNetLemmatizer()

def text_preprocess(text):
  #lowercase
    text = str(text).lower()
  #remove punctuations
    text= re.sub(r'[^a-zA-Z\s]','',text)
  #tokenization
    words = text.split()
  #Remove Stopwords
    words = [word for word in words if word not in stop_words]
  #lemmatization
    words = [lammatizer.lemmatize(word) for word in words]

    return ' '.join(words)

dfn['tags'] = dfn['tags'].apply(text_preprocess)

dfn = dfn.reset_index(drop = True)

indices = pd.Series(dfn.index, dfn['title']).drop_duplicates()

from sklearn.feature_extraction.text import TfidfVectorizer

tdidf = TfidfVectorizer(max_features = 50000, ngram_range = (1,2), stop_words = 'english')

tdidf_matrix = tdidf.fit_transform(dfn['tags'])

tdidf_matrix

from sklearn.metrics.pairwise import cosine_similarity

def recommend(title, n=10):
  if title not in indices:
     return ['Movie not found']

  idx = indices[title]
  sim_score = cosine_similarity(tdidf_matrix[idx], tdidf_matrix).flatten()
  similar_idx = sim_score.argsort()[::-1][1:n+1]
  return dfn['title'].iloc[similar_idx]

recommend('Avatar')

import pickle
pickle.dump(tdidf_matrix,open('tdidf_matrix.pkl','wb'))
pickle.dump(indices,open('indices.pkl','wb'))
df.to_pickle('df.pkl')
pickle.dump(tdidf,open('tdidf.pkl','wb'))